(ns cn.li.mcmod.gui.adapter.container-registry
  (:require [cn.li.mcmod.gui.adapter.platform-registry :as platform-registry]))

(defn set-client-container! [container] (platform-registry/invoke-platform! :set-client-container! container))
(defn clear-client-container! [] (platform-registry/invoke-platform! :clear-client-container!))
(defn get-client-container [] (platform-registry/invoke-platform! :get-client-container))
(defn register-active-container! [container] (platform-registry/invoke-platform! :register-active-container! container))
(defn unregister-active-container! [container] (platform-registry/invoke-platform! :unregister-active-container! container))
(defn register-player-container! [player container] (platform-registry/invoke-platform! :register-player-container! player container))
(defn unregister-player-container! [player] (platform-registry/invoke-platform! :unregister-player-container! player))
(defn get-player-container [player] (platform-registry/invoke-platform! :get-player-container player))
(defn get-player-container-from-active [player] (platform-registry/invoke-platform! :get-player-container-from-active player))
(defn get-container-for-menu [menu] (platform-registry/invoke-platform! :get-container-for-menu menu))
(defn get-container-by-id [container-id] (platform-registry/invoke-platform! :get-container-by-id container-id))
(defn get-menu-container-id [menu] (platform-registry/invoke-platform! :get-menu-container-id menu))
(defn register-menu-container! [menu container] (platform-registry/invoke-platform! :register-menu-container! menu container))
(defn unregister-menu-container! [menu] (platform-registry/invoke-platform! :unregister-menu-container! menu))
(defn register-container-by-id! [container-id container] (platform-registry/invoke-platform! :register-container-by-id! container-id container))
(defn unregister-container-by-id! [container-id] (platform-registry/invoke-platform! :unregister-container-by-id! container-id))
(defn safe-tick! [container] (platform-registry/invoke-platform! :safe-tick! container))
(defn safe-validate [container player] (platform-registry/invoke-platform! :safe-validate container player))
(defn safe-sync! [container] (platform-registry/invoke-platform! :safe-sync! container))
(defn safe-close! [container] (platform-registry/invoke-platform! :safe-close! container))
(defn slot-count [container] (platform-registry/invoke-platform! :slot-count container))
(defn slot-get-item [container idx] (platform-registry/invoke-platform! :slot-get-item container idx))
(defn slot-set-item! [container idx item] (platform-registry/invoke-platform! :slot-set-item! container idx item))
(defn slot-changed! [container idx] (platform-registry/invoke-platform! :slot-changed! container idx))
(defn slot-can-place? [container idx stack] (platform-registry/invoke-platform! :slot-can-place? container idx stack))
(defn get-container-type [container] (platform-registry/invoke-platform! :get-container-type container))
(defn node-container? [container] (platform-registry/invoke-platform! :node-container? container))
(defn matrix-container? [container] (platform-registry/invoke-platform! :matrix-container? container))
(defn get-gui-id-for-container [container] (platform-registry/invoke-platform! :get-gui-id-for-container container))
