(ns cn.li.mc262.runtime.entity-motion-core)
(defn init! [& _] nil)
(defn setup! [& _] nil)
(defn break-block! [& _] nil)
(defn spawn-projectile-in-level! [& _] nil)
(defn create-tile-inventory-adapter [& _] nil)
(defn execute-send-message-action [& _] nil)
(defn execute-action [& _] nil)
(defn apply-effect! [& _] nil)
(defn remove-effect! [& _] nil)