(ns cn.li.mcmod.client.ui-hooks
  "Client UI/screen hook surface (compat wrapper)."
  (:require [cn.li.mcmod.runtime.hooks.client-ui :as client-ui]))

(def client-build-overlay-plan client-ui/client-build-overlay-plan)
(def client-build-hud-render-data client-ui/client-build-hud-render-data)
(def client-open-skill-tree-screen! client-ui/client-open-skill-tree-screen!)
(def client-build-skill-tree-draw-ops client-ui/client-build-skill-tree-draw-ops)
(def client-handle-skill-tree-hover! client-ui/client-handle-skill-tree-hover!)
(def client-handle-skill-tree-click! client-ui/client-handle-skill-tree-click!)
(def client-close-skill-tree-screen! client-ui/client-close-skill-tree-screen!)
(def client-open-preset-editor-screen! client-ui/client-open-preset-editor-screen!)
(def client-build-preset-editor-draw-ops client-ui/client-build-preset-editor-draw-ops)
(def client-handle-preset-editor-click! client-ui/client-handle-preset-editor-click!)
(def client-close-preset-editor-screen! client-ui/client-close-preset-editor-screen!)
(def client-open-location-teleport-screen! client-ui/client-open-location-teleport-screen!)
(def client-build-location-teleport-draw-ops client-ui/client-build-location-teleport-draw-ops)
(def client-handle-location-teleport-click! client-ui/client-handle-location-teleport-click!)
(def client-close-location-teleport-screen! client-ui/client-close-location-teleport-screen!)
(def client-open-saved-position-screen! client-ui/client-open-saved-position-screen!)
(def client-build-saved-position-draw-ops client-ui/client-build-saved-position-draw-ops)
(def client-handle-saved-position-hover! client-ui/client-handle-saved-position-hover!)
(def client-handle-saved-position-click! client-ui/client-handle-saved-position-click!)
(def client-handle-saved-position-char-typed! client-ui/client-handle-saved-position-char-typed!)
(def client-close-saved-position-screen! client-ui/client-close-saved-position-screen!)
