modLoader="javafml"
loaderVersion="[36,)")
license="MIT"
issueTrackerURL="https://example.com/issues"

[[mods]]
modId="my_mod"
version="${file.jarVersion}"
displayName="My Mod (Clojure)"
authors="You"
description='''
Demo mod core in Clojure with Forge 1.16.5 adapter.
'''

[[dependencies.my_mod]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.my_mod]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"
