(ns cn.li.mcmod.protocol.core
  "Shared registry abstraction for atom-backed metadata registries.")

(defprotocol IRegistry
  (snapshot [this])
  (swap-state! [this f])
  (reset-state! [this new-state]))

;; Use reify instead of deftype/extend-protocol — the latter routes
;; through Clojure AOT class generation which can lose track of local
;; parameter symbols (e.g. `f`) inside the generated bytecode, causing
;; "Unable to resolve symbol" at MC-BOOTSTRAP load time.
;; reify captures locals as ordinary closures, which AOT handles correctly.

(defn atom-registry
  [initial-state]
  (let [state-ref (atom initial-state)]
    (reify IRegistry
      (snapshot [_]
        @state-ref)
      (swap-state! [_ f]
        (swap! state-ref f))
      (reset-state! [_ new-state]
        (reset! state-ref new-state)))))

(defn var-root-registry
  [state-var]
  (let [lock (Object.)]
    (reify IRegistry
      (snapshot [_]
        (var-get state-var))
      (swap-state! [_ f]
        (locking lock
          (let [next-state (f (var-get state-var))]
            (alter-var-root state-var (constantly next-state))
            next-state)))
      (reset-state! [_ new-state]
        (locking lock
          (alter-var-root state-var (constantly new-state))
          new-state)))))

(defn lookup
  ([registry k]
   (get (snapshot registry) k))
  ([registry k default]
   (get (snapshot registry) k default)))

(defn lookup-in
  [registry path]
  (get-in (snapshot registry) path))
