(ns cn.li.mcmod.ui.types)
(definterface IUiRtState
  (^Object clockMsSig []) (^Object partialTicksSig []) (^Object gameTicksSig [])
  (^java.util.ArrayList nodesVec []) (^Object idToNode []) (^void setIdToNode [^Object m])
  (^java.util.ArrayList dirtyBindingsVec [])
  (^objects tapeArr []) (^void setTapeArr [^objects arr])
  (^boolean isTreeDirty []) (^void setTreeDirty [^boolean v])
  (^double getScreenW []) (^void setScreenW [^double v])
  (^double getScreenH []) (^void setScreenH [^double v])
  (^Object getHoveredIdx []) (^void setHoveredIdx [^Object v])
  (^Object getFocusIdx []) (^void setFocusIdx [^Object v])
  (^Object getDragNodeIdx []) (^void setDragNodeIdx [^Object v])
  (^boolean isDragging []) (^void setDragging [^boolean v])
  (^double getDragStartMx []) (^void setDragStartMx [^double v])
  (^double getDragStartMy []) (^void setDragStartMy [^double v])
  (^long getDragStartMs []) (^void setDragStartMs [^long v])
  (^Object eventsMap []) (^void setEventsMap [^Object m])
  (^Object userSignalsMap []) (^void setUserSignalsMap [^Object m])
  (^boolean isDisposed []) (^void setDisposed [^boolean v]))
