(ns cn.li.ac.ability.client.screens.preset-editor-reactive
  "Preset Editor reactive UI — fully aligned with AcademyCraft PresetEditUI.java.
   XML-driven layout, horizontal carousel with lerp animation, selector popup
   with background/glow/tooltip, full-screen dark overlay, ESC to close.

   Exact upstream constants:
   - STEP=125, TRANSIT_TIME=0.35, MAX_ALPHA=255, MIN_ALPHA=77 (0.3)
   - MAX_SCALE=1.0, MIN_SCALE=0.8
   - CRL_BACK=(49,49,49,200), CRL_WHITE=(1,1,1,0.6), CRL_GLOW=(1,1,1,0.2)
   - Selector: MAX_PER_ROW=4, MARGIN=2.5, SIZE=15, STEP=18"
  (:require [cn.li.ac.ability.client.screens.preset-editor :as logic]
            [cn.li.ac.ability.client.api :as api]
            [cn.li.ac.ability.registry.skill-query :as skill-query]
            [cn.li.ac.config.modid :as modid]
            [cn.li.mcmod.client.platform-bridge :as bridge]
            [cn.li.mcmod.hooks.core :as runtime-hooks]
            [cn.li.mcmod.i18n :as i18n]
            [cn.li.mcmod.ui.core :as ui]
            [cn.li.mcmod.ui.events :as events]
            [cn.li.mcmod.ui.node :as node]
            [cn.li.mcmod.ui.runtime :as rt]
            [cn.li.mcmod.ui.signal :as sig]
            [cn.li.mcmod.ui.xml :as ui-xml]
            [cn.li.mcmod.util.log :as log])
  (:import [cn.li.mcmod.uipojo.runtime UiRt]
           [cn.li.mcmod.ui.node INode]
           [java.util HashMap]))

;; Forward declare — used by build-selector! before definition
(declare refresh-ui!)

;; ============================================================================
;; Carousel constants (matching upstream PresetEditUI.java exactly)
;; ============================================================================

(def ^:private step 125.0)        ;; horizontal offset between pages
(def ^:private transit-time 0.35) ;; slide transition duration (seconds)
(def ^:private max-alpha 1.0)     ;; Colors.f2i(1f)
(def ^:private min-alpha 0.3)     ;; Colors.f2i(0.3f)
(def ^:private max-scale 1.0)
(def ^:private min-scale 0.8)

;; Selector constants (matching upstream Selector inner class exactly)
(def ^:private sel-max-per-row 4)
(def ^:private sel-margin 2.5)
(def ^:private sel-size 15.0)
(def ^:private sel-step (+ sel-size 3.0))

;; Selector colors (matching upstream CRL_* constants)
(def ^:private crl-back  0xC8313131)  ;; (49,49,49,200)
(def ^:private crl-glow  0x33FFFFFF)  ;; (1,1,1,0.2) — hover tint + tooltip glow

;; ============================================================================
;; State tracking per-session (Framework-backed for lifecycle safety)
;; ============================================================================

(defonce ^:private ^HashMap active-by-session (HashMap.))

(defn- track-active! [owner ^UiRt r]
  (when-let [uuid (or (:player-uuid owner) (nth (logic/editor-owner-key owner) 2 nil))]
    (when-let [session-id (:client-session-id owner)]
      (.put active-by-session [session-id uuid] {:rt r :owner owner}))))

(defn- untrack-active! [owner]
  (when-let [uuid (or (:player-uuid owner) (nth (logic/editor-owner-key owner) 2 nil))]
    (when-let [session-id (:client-session-id owner)]
      (.remove active-by-session [session-id uuid]))))

(defn- cached-owner [^UiRt r]
  (or (:owner (rt/user-signal r :owner))
      (when-let [session-id (runtime-hooks/client-session-id)]
        (some (fn [entry]
                (let [[sid _] (.getKey ^java.util.Map$Entry entry)]
                  (when (= sid session-id) (:owner (.getValue ^java.util.Map$Entry entry)))))
              (.entrySet active-by-session)))))

;; ============================================================================
;; Helpers
;; ============================================================================

(defn- local [key]
  ;; Lang keys are generated by datagen as "gui.<modid>.preset_edit.*" — the
  ;; upstream-style "ac.gui.preset_edit.*" keys do not exist in the lang files.
  (let [k (str "gui." modid/MOD-ID ".preset_edit." key)
        translated (i18n/translate k)]
    (if (= translated k) key translated)))

(defn- now-sec []
  "Current time in fractional seconds."
  (/ (double (System/currentTimeMillis)) 1000.0))

(defn- lerp-d [a b t]
  (+ (double a) (* (- (double b) (double a)) (max 0.0 (min 1.0 (double t))))))

;; ============================================================================
;; Carousel animation state
;; ============================================================================

(definterface ICarouselAnim
  (^long activeIndex [])
  (setActiveIndex [^long value])
  (^long fromIndex [])
  (setFromIndex [^long value])
  (^long toIndex [])
  (setToIndex [^long value])
  (^double transitStart [])
  (setTransitStart [^double value])
  (^boolean transiting [])
  (setTransiting [^boolean value]))

(deftype CarouselAnim
  [^:unsynchronized-mutable ^long active
   ^:unsynchronized-mutable ^long from
   ^:unsynchronized-mutable ^long to
   ^:unsynchronized-mutable ^double start
   ^:unsynchronized-mutable ^boolean in-transit]
  ICarouselAnim
  (activeIndex [_] active)
  (setActiveIndex [_ value] (set! active value))
  (fromIndex [_] from)
  (setFromIndex [_ value] (set! from value))
  (toIndex [_] to)
  (setToIndex [_ value] (set! to value))
  (transitStart [_] start)
  (setTransitStart [_ value] (set! start value))
  (transiting [_] in-transit)
  (setTransiting [_ value] (set! in-transit value)))

(defn- carousel-anim [^UiRt r]
  (or (rt/user-signal r :carousel-anim)
      (let [a (CarouselAnim. 0 0 0 0.0 false)]
        (rt/put-user-signal! r :carousel-anim a)
        a)))

(defn- start-transit! [^UiRt r from-idx to-idx]
  (let [^CarouselAnim anim (carousel-anim r)]
    (.setFromIndex anim (long from-idx))
    (.setToIndex anim (long to-idx))
    (.setTransitStart anim (now-sec))
    (.setTransiting anim true)))

(defn- finish-transit! [^UiRt r]
  (let [^CarouselAnim anim (carousel-anim r)]
    (.setTransiting anim false)
    (.setActiveIndex anim (.toIndex anim))))

;; ============================================================================
;; Slot info update — skill icon + name from preset data
;; ============================================================================

(defn- clear-selector! [^UiRt r]
  (when-let [^INode sel (rt/node-by-id r :selector)]
    (.setVisible sel false)
    (.setFlag sel node/FLAG-LAYOUT-DIRTY)
    (rt/mark-tree-dirty! r)
    (rt/clear-children! r sel))
  (rt/put-user-signal! r :selector-open false)
  (rt/put-user-signal! r :selector-slot nil)
  (rt/put-user-signal! r :sel-tooltip-state nil))

(defn- selector-open? [^UiRt r]
  (boolean (rt/user-signal r :selector-open)))

(defn- slot-tex-path [skill-id]
  ;; Upstream updateInfo: empty slot → Resources.TEX_EMPTY (transparent null
  ;; texture), i.e. draw NOTHING. Empty :src makes render-image! skip the node.
  (if skill-id
    (or (skill-query/get-skill-icon-path skill-id)
        (modid/asset-path "textures" "missing.png"))
    ""))

;; ============================================================================
;; Alignment helpers — visibility (tape-aware), master alpha, glow 8-patch
;; ============================================================================

(defn- set-node-visible! [^UiRt r ^INode n visible?]
  ;; Visibility participates in tape flattening — a toggle must mark the tree
  ;; dirty (change-guarded: rebuild cost only on transition frames).
  (when (and n (not= (boolean visible?) (.isVisible n)))
    (.setVisible n (boolean visible?))
    (.setFlag n node/FLAG-RENDER-DIRTY)
    (rt/mark-tree-dirty! r)))

(defn- set-image-alpha! [^INode n ^double a]
  (when (and n (not (== a (.getDSlot n 0))))
    (.setDSlot n 0 a)
    (.setFlag n node/FLAG-RENDER-DIRTY)))

(defn- set-text-alpha! [^UiRt r ^INode n ^double a]
  ;; Upstream AlphaAssign writes TextBox option.color.a — here: white RGB with
  ;; the master alpha in the high byte.
  (when n
    (ui/set-node-prop! r n :color
                       (bit-or 0x00FFFFFF
                               (bit-shift-left (long (* 255.0 (max 0.0 (min 1.0 a)))) 24)))))

(defn- glow-tex [suffix]
  (modid/asset-path "textures" (str "guis/glow_" suffix ".png")))

(defn- build-glow!
  "8-patch glow ring around a rect — upstream ACRenderingHelper.drawGlow.
   Returns {suffix INode} so callers can retarget widths later."
  [^UiRt r ^INode parent id-prefix x y w h size alpha]
  (into {}
    (for [[suffix gx gy gw gh] [["lu"    (- x size) (- y size) size size]
                                ["up"    x          (- y size) w    size]
                                ["ru"    (+ x w)    (- y size) size size]
                                ["left"  (- x size) y          size h]
                                ["right" (+ x w)    y          size h]
                                ["ld"    (- x size) (+ y h)    size size]
                                ["down"  x          (+ y h)    w    size]
                                ["rd"    (+ x w)    (+ y h)    size size]]]
      [suffix (rt/build-child! r
                {:kind :image
                 :props {:id (keyword (str id-prefix suffix))
                         :x gx :y gy :w gw :h gh
                         :src (glow-tex suffix)
                         :alpha alpha}}
                parent)])))

;; ============================================================================
;; Per-page node cache — resolved once after build, drives alpha/hover updates
;; ============================================================================

(defn- collect-page-nodes! [^UiRt r]
  (mapv
    (fn [page-idx]
      (let [nid (fn [suffix] (rt/node-by-id r (keyword (str "preset-" page-idx suffix))))
            rows (mapv (fn [slot-idx]
                         (let [^INode row (nid (str "-" slot-idx))]
                           {:row row
                            :bg (nid (str "-" slot-idx "-bg"))
                            :icon (nid (str "-" slot-idx "-icon"))
                            :text (nid (str "-" slot-idx "-text"))
                            ;; Row subtree idx range for hover hit checks:
                            ;; children (bg/icon/text) register right after
                            ;; the row group in depth-first build order.
                            :lo (.getIdx row)
                            :hi (+ (.getIdx row) 3)}))
                       (range 4))]
        {:page (nid "")
         :back (nid "-back")
         :title (nid "-title")
         :rows rows}))
    (range 4)))

(defn- page-nodes [^UiRt r]
  (or (rt/user-signal r :page-nodes)
      (let [pn (collect-page-nodes! r)]
        (rt/put-user-signal! r :page-nodes pn)
        (rt/put-user-signal! r :page-alpha (double-array [(- 1.0) (- 1.0) (- 1.0) (- 1.0)]))
        pn)))

(defn- apply-page-alpha! [^UiRt r page page-idx ^double alpha]
  ;; Upstream AlphaAssign: master page alpha propagated to every child
  ;; DrawTexture + TextBox. Change-guarded per page.
  (let [^doubles last-alpha (rt/user-signal r :page-alpha)]
    (when-not (== alpha (aget last-alpha page-idx))
      (aset last-alpha page-idx alpha)
      (set-image-alpha! (:back page) alpha)
      (set-text-alpha! r (:title page) alpha)
      (doseq [{:keys [bg icon text]} (:rows page)]
        (set-image-alpha! bg alpha)
        (set-image-alpha! icon alpha)
        (set-text-alpha! r text alpha)))))

(defn- update-page-slot! [^UiRt r page-idx slot-idx slot-info]
  "Update one slot's icon and text from slot-info map or nil."
  (let [icon-node-id (keyword (str "preset-" page-idx "-" slot-idx "-icon"))
        text-node-id (keyword (str "preset-" page-idx "-" slot-idx "-text"))
        skill-id (:skill-id slot-info)
        skill-name (:skill-name slot-info)]
    (when-let [^INode icon (rt/node-by-id r icon-node-id)]
      (ui/set-node-prop! r icon :src (slot-tex-path skill-id)))
    (when-let [^INode text (rt/node-by-id r text-node-id)]
      (ui/set-node-prop! r text :text (or skill-name "")))))

(defn- update-page-slots! [^UiRt r page-idx slots]
  (doseq [slot-idx (range 4)]
    (update-page-slot! r page-idx slot-idx (nth slots slot-idx nil))))

(defn- update-page-title! [^UiRt r page-idx]
  (when-let [^INode title (rt/node-by-id r (keyword (str "preset-" page-idx "-title")))]
    (ui/set-node-prop! r title :text (str (local "tag") (inc page-idx)))))

;; ============================================================================
;; Selector popup — fully aligned with upstream Selector inner class
;; ============================================================================

(defn- build-selector! [^UiRt r page-idx slot-idx mx my]
  (clear-selector! r)
  (let [owner (cached-owner r)
        rd (when owner (logic/build-preset-editor-render-data owner))
        available (vec (:available-skills rd))
        ;; Items: -1 = remove (matching upstream cancel button), then skills
        items (into [{:id -1 :icon (modid/asset-path "textures" "guis/preset_settings/cancel.png")
                      :name (local "skill_remove")}]
                    (mapv (fn [s]
                            {:id (:ctrl-id s) :skill-id (:skill-id s)
                             :icon (or (:skill-icon s) (modid/asset-path "textures" "missing.png"))
                             :name (:skill-name s) :cat-id (:cat-id s) :ctrl-id (:ctrl-id s)})
                          available))
        n (count items)
        rows (int (Math/ceil (/ (double n) sel-max-per-row)))
        cols (min n sel-max-per-row)
        sel-w (+ (* 2 sel-margin) (* sel-step (dec cols)) sel-size)
        sel-h (+ (* 2 sel-margin) (* sel-step (dec rows)) sel-size)]
    (when-let [^INode sel-node (rt/node-by-id r :selector)]
      ;; Upstream: selector top-left AT the mouse position; tooltip floats
      ;; above it at negative y.
      (.setX sel-node (double mx))
      (.setY sel-node (double my))
      ;; Group kinds have no :w/:h prop-writers — size via INode setters.
      (.setW sel-node (double sel-w))
      (.setH sel-node (double sel-h))
      (.setVisible sel-node true)
      (.setFlag sel-node node/FLAG-LAYOUT-DIRTY)
      (rt/mark-tree-dirty! r)
      ;; Glow ring (upstream drawGlow CRL_WHITE, thickness 1) + background
      (build-glow! r sel-node "sel-glow-" 0.0 0.0 sel-w sel-h 1.0 0.6)
      (rt/build-child! r
        {:kind :box :props {:id :sel-bg :x 0.0 :y 0.0 :w sel-w :h sel-h :fill crl-back}}
        sel-node)
      ;; Tooltip ABOVE the selector (upstream: rect (0,-13.5,len+6,11.5),
      ;; glow CRL_GLOW, text at (3,-12) 9pt #FFBBBBBB, content = hovered
      ;; item's name — updated per frame by update-selector-tooltip!).
      (let [default-text (local "skill_select")
            len (double (or (bridge/font-width (str default-text)) 40.0))
            tt-w (+ len 6.0)
            ^INode tt-group (rt/build-child! r
                              {:kind :group
                               :props {:id :sel-tooltip :x 0.0 :y -13.5 :w tt-w :h 11.5}}
                              sel-node)
            glow (build-glow! r tt-group "sel-tt-glow-" 0.0 0.0 tt-w 11.5 1.0 0.2)
            ^INode tt-bg (rt/build-child! r
                           {:kind :box :props {:id :sel-tooltip-bg :x 0.0 :y 0.0
                                               :w tt-w :h 11.5 :fill crl-back}}
                           tt-group)
            ^INode tt-text (rt/build-child! r
                             {:kind :text :props {:id :sel-tooltip-text :x 3.0 :y 1.5
                                                  :w 200.0 :h 9.0
                                                  :text default-text :font-size 9.0
                                                  :color 0xFFBBBBBB}}
                             tt-group)
            sel-items (volatile! [])]
        ;; Selector item grid
        (doseq [[i item] (map-indexed vector items)]
          (let [row (quot i sel-max-per-row)
                col (rem i sel-max-per-row)
                item-x (+ sel-margin (* col sel-step))
                item-y (+ sel-margin (* row sel-step))
                item-id (keyword (str "sel-" i))
                ^INode item-node
                (rt/build-child! r
                  {:kind :group
                   :props {:id item-id :x item-x :y item-y :w sel-size :h sel-size}
                   :children
                   [{:kind :image
                     :props {:id (keyword (str (name item-id) "-icon"))
                             :x 0.0 :y 0.0 :w sel-size :h sel-size :src (:icon item)}}
                    {:kind :box
                     :props {:id (keyword (str (name item-id) "-hit"))
                             :x 0.0 :y 0.0 :w sel-size :h sel-size
                             ;; Upstream Tint: idle 0 → hover white 0.2
                             :fill 0x00000000 :hover-tint crl-glow}}]}
                  sel-node)]
            ;; Hover→tooltip mapping: item subtree = group + icon + hit box.
            (vswap! sel-items conj {:lo (.getIdx item-node)
                                    :hi (+ (.getIdx item-node) 2)
                                    :name (:name item)})
            ;; Click handler — immediate save + close (matching upstream SelHandler)
            (events/on! r item-id :left-click
              (fn [_ _ _]
                (if (= -1 (:id item))
                  ;; Remove → clear slot (upstream cancel button)
                  (when owner
                    (api/req-set-preset-slot! owner page-idx slot-idx nil nil nil))
                  ;; Assign skill → immediate save (upstream onEdit)
                  (when owner
                    (api/req-set-preset-slot! owner page-idx slot-idx
                                             (:cat-id item) (:ctrl-id item) nil)))
                (clear-selector! r)
                (refresh-ui! r (cached-owner r))))))
        (rt/put-user-signal! r :sel-tooltip-state
          {:bg tt-bg :text tt-text :glow glow :items @sel-items
           :last (object-array [nil])}))
      ;; Track which slot the selector is open for
      (rt/put-user-signal! r :selector-open true)
      (rt/put-user-signal! r :selector-slot [page-idx slot-idx]))))

(defn- update-selector-tooltip!
  "Per-frame: tooltip shows the hovered item's name (upstream Selector
   FrameEvent), falling back to the generic hint. Width follows the text
   (upstream: len + 6) — bg + glow ring retargeted on change only."
  [^UiRt r]
  (when (selector-open? r)
    (when-let [{:keys [^INode bg ^INode text glow items ^objects last]}
               (rt/user-signal r :sel-tooltip-state)]
      (let [hovered (long (rt/hovered-idx r))
            nm (or (some (fn [{:keys [lo hi name]}]
                           (when (<= (long lo) hovered (long hi)) name))
                         items)
                   (local "skill_select"))]
        (when-not (= nm (aget last 0))
          (aset last 0 nm)
          (ui/set-node-prop! r text :text (str nm))
          (let [w (+ 6.0 (double (or (bridge/font-width (str nm)) 40.0)))]
            (.setW bg w)
            (.setFlag bg node/FLAG-LAYOUT-DIRTY)
            (doseq [suffix ["up" "down"]]
              (when-let [^INode gnode (get glow suffix)]
                (.setW gnode w)
                (.setFlag gnode node/FLAG-LAYOUT-DIRTY)))
            (doseq [suffix ["ru" "right" "rd"]]
              (when-let [^INode gnode (get glow suffix)]
                (.setX gnode w)
                (.setFlag gnode node/FLAG-LAYOUT-DIRTY)))))))))

;; ============================================================================
;; Page refresh — react to preset data changes
;; ============================================================================

(defn- page-x-from-active [page-idx active-idx]
  "Upstream getXFor(i, active): STEP * (i - active). Active at center (0)."
  (* step (- page-idx active-idx)))

(defn- refresh-carousel! [^UiRt r owner]
  (when-let [rd (logic/build-preset-editor-render-data owner)]
    (let [all-slots (:all-preset-slots rd)
          selected-preset (:selected-preset rd)
          ^CarouselAnim anim (carousel-anim r)]
      (doseq [page-idx (range 4)]
        (let [page-slots (get all-slots page-idx (vec (repeat 4 nil)))]
          (update-page-slots! r page-idx page-slots)
          (update-page-title! r page-idx)))
      ;; Update carousel target: center on selected-preset (upstream updatePosForeground)
      (.setActiveIndex anim (long selected-preset)))))

;; ============================================================================
;; Animated carousel tick — matching upstream updateTransit + updatePosForeground
;; ============================================================================

(defn- apply-page-transform! [^UiRt r page-idx x scale alpha]
  "Position one carousel page — upstream Page.updatePosition: x + scale +
   master alpha (AlphaAssign). ALL pages stay visible (side pages dimmed to
   MIN_ALPHA, never hidden)."
  (let [pages (page-nodes r)
        page (nth pages page-idx)
        ^INode pn (:page page)]
    (when pn
      (when (or (not (== (double x) (.getX pn)))
                (not (== (double scale) (.getScale pn))))
        (.setX pn (double x))
        (.setScale pn (double scale))
        (.setFlag pn node/FLAG-LAYOUT-DIRTY))
      (when-not (.isVisible pn)
        (set-node-visible! r pn true))
      (apply-page-alpha! r page page-idx (double alpha)))))

(defn- update-hover-highlights! [^UiRt r active transiting?]
  "Upstream HintHandler FrameEvent: slot highlight (selected.png) enabled only
   when its page is active AND the mouse hovers the row."
  (let [pages (page-nodes r)
        hovered (long (rt/hovered-idx r))]
    (doseq [page-idx (range 4)]
      (let [active? (and (not transiting?) (= page-idx active))]
        (doseq [{:keys [^INode bg lo hi]} (:rows (nth pages page-idx))]
          (set-node-visible! r bg
            (boolean (and active? (<= (long lo) hovered (long hi))))))))))

(defn- sync-root-to-screen!
  "Upstream CGUI aligns widgets against the SCREEN (CGui.resize sets the root
   to screen size); our layout aligns children against the PARENT node. The
   XML root is size 0 — without this sync the root collapses to a point at
   screen center, so left/top children (blackout, screen title) render from
   MID-SCREEN (the 'misplaced translucent panel'). Center-aligned pages were
   only coincidentally unaffected ((0-w)/2 vs (sw-w)/2 both center them)."
  [^UiRt r]
  (let [^INode root (rt/node-by-idx r 0)
        sw (rt/screen-w r)
        sh (rt/screen-h r)]
    (when (and root (pos? sw)
               (or (not (== sw (.getW root)))
                   (not (== sh (.getH root)))))
      (.setW root sw)
      (.setH root sh)
      (.setFlag root node/FLAG-LAYOUT-DIRTY)
      (when-let [^INode blackout (rt/node-by-id r :blackout)]
        (.setW blackout sw)
        (.setH blackout sh)
        (.setFlag blackout node/FLAG-LAYOUT-DIRTY)))))

(defn- attach-carousel-tick! [^UiRt r]
  (let [clock (rt/clock-ms-sig r)
        ^CarouselAnim anim (carousel-anim r)
        computed (sig/computed-o [clock]
                   (fn [_]
                     (sync-root-to-screen! r)
                     (let [active (.activeIndex anim)
                           from (.fromIndex anim)
                           to (.toIndex anim)
                           start-time (.transitStart anim)
                           transiting? (.transiting anim)]
                       (if transiting?
                         ;; Upstream TransitPage.updatePosition: lerp x/scale/alpha
                         ;; for from/to pages; other pages stay at MIN — VISIBLE.
                         (let [elapsed (- (now-sec) (double start-time))
                               progress (min 1.0 (/ elapsed transit-time))]
                           (doseq [page-idx (range 4)]
                             (let [x0 (page-x-from-active page-idx from)
                                   x1 (page-x-from-active page-idx to)
                                   x (lerp-d x0 x1 progress)
                                   from? (= page-idx from)
                                   to? (= page-idx to)
                                   scale (cond
                                           from? (lerp-d max-scale min-scale progress)
                                           to?   (lerp-d min-scale max-scale progress)
                                           :else min-scale)
                                   alpha (cond
                                           from? (lerp-d max-alpha min-alpha progress)
                                           to?   (lerp-d min-alpha max-alpha progress)
                                           :else min-alpha)]
                               (apply-page-transform! r page-idx x scale alpha)))
                           (when (>= progress 1.0)
                             (finish-transit! r)
                             (doseq [page-idx (range 4)]
                               (let [active? (= page-idx to)]
                                 (apply-page-transform! r page-idx
                                   (page-x-from-active page-idx to)
                                   (if active? max-scale min-scale)
                                   (if active? max-alpha min-alpha))))))
                         ;; Not transiting — upstream updatePosForeground
                         (doseq [page-idx (range 4)]
                           (let [active? (= page-idx active)]
                             (apply-page-transform! r page-idx
                               (page-x-from-active page-idx active)
                               (if active? max-scale min-scale)
                               (if active? max-alpha min-alpha)))))
                       ;; Per-frame hover feedback (highlight + selector tooltip)
                       (update-hover-highlights! r (if transiting? to active) transiting?)
                       (update-selector-tooltip! r))
                     nil))]
    (let [^INode anchor (rt/node-by-id r :preset-0)]
      (when anchor
        (let [b (sig/bind! computed anchor
                           (fn [_node source]
                             ;; ComputedO is LAZY: the per-frame carousel side
                             ;; effects live in recompute(), which only runs on
                             ;; sGet. A no-op applyFn never pulls → the computed
                             ;; stays dirty forever and NOTHING here ever
                             ;; executes (x/scale/alpha/hover were all dead).
                             (sig/sget-o source))
                           (rt/get-dirty-bindings-q r))]
          (rt/register-binding! r (.getIdx anchor) b))))))

;; ============================================================================
;; Wire slot clicks → open Selector (matching upstream HintHandler)
;; ============================================================================

(defn- switch-to-page! [^UiRt r owner page-idx]
  (let [^CarouselAnim anim (carousel-anim r)]
    (when (not= page-idx (.activeIndex anim))
      (clear-selector! r)
      (start-transit! r (.activeIndex anim) page-idx)
      ;; View-local edit target only — upstream startTransit never touches the
      ;; server-side active preset.
      (logic/on-preset-tab-click owner page-idx)
      (refresh-carousel! r owner))))

(defn- wire-slot-clicks! [^UiRt r owner page-idx]
  (doseq [slot-idx (range 4)]
    (let [slot-id (keyword (str "preset-" page-idx "-" slot-idx))]
      (events/on! r slot-id :left-click
        (fn [_ _ evt]
          (let [^CarouselAnim anim (carousel-anim r)]
            (when-not (.transiting anim)
              (cond
                ;; Upstream: if selector open, dispose it (click same slot = close)
                (selector-open? r)
                (clear-selector! r)

                ;; Upstream: if page is active, open selector at mouse position
                (= page-idx (.activeIndex anim))
                (let [mx (double (or (:x evt) 0))
                      my (double (or (:y evt) 0))]
                  (build-selector! r page-idx slot-idx mx my))

                ;; Upstream HintHandler else-branch: a row click on an INACTIVE
                ;; page transits to that page. Rows cover almost the whole page,
                ;; and click bubbling stops at the first handler — without this
                ;; branch side-page clicks land here and die silently.
                :else
                (switch-to-page! r owner page-idx)))))))))

;; ============================================================================
;; Wire page clicks → switch to that preset (matching upstream startTransit)
;; ============================================================================

(defn- wire-page-clicks! [^UiRt r owner]
  (doseq [page-idx (range 4)]
    (let [page-id (keyword (str "preset-" page-idx))]
      (events/on! r page-id :left-click
        (fn [_ _ _]
          (let [^CarouselAnim anim (carousel-anim r)]
            (when-not (.transiting anim)
              (if (= page-idx (.activeIndex anim))
                (when (selector-open? r) (clear-selector! r))
                (switch-to-page! r owner page-idx)))))))))

;; ============================================================================
;; Public API
;; ============================================================================

(defn refresh-ui!
  "Rebuild carousel + slot contents from current editor + player state."
  [^UiRt r owner]
  (when owner
    (refresh-carousel! r owner)
    nil))

(defn refresh-active-screen!
  "Called when server preset data syncs while the editor is open."
  [player-uuid]
  (when-let [session-id (runtime-hooks/client-session-id)]
    (when-let [{:keys [rt owner]} (.get active-by-session [session-id player-uuid])]
      (refresh-ui! rt owner))))

(defn- load-page-spec []
  (ui-xml/load-spec (modid/namespaced-path "guis/new/preset_edit.xml")))

(defn create-runtime
  "Build reactive preset editor runtime fully matching upstream AcademyCraft UX."
  [owner]
  (let [r (rt/create-runtime)
        spec (load-page-spec)
        _ (rt/build! r spec)
        _ (logic/open-screen! owner)]
    (rt/put-user-signal! r :owner owner)
    (track-active! owner r)
    ;; XML text nodes carry raw keys — translate the static screen title here.
    (when-let [^INode title (rt/node-by-id r :screen-title)]
      (ui/set-node-prop! r title :text (local "name")))
    ;; Wire all interactions
    (wire-page-clicks! r owner)
    (doseq [page-idx (range 4)]
      (wire-slot-clicks! r owner page-idx))
    ;; Carousel animation — matching upstream updateTransit + updatePosForeground
    (attach-carousel-tick! r)
    ;; Initial state
    (let [^CarouselAnim anim (carousel-anim r)]
      (.setActiveIndex anim (long (:selected-preset
                                    (or (logic/build-preset-editor-render-data owner)
                                        {:selected-preset 0})))))
    (refresh-ui! r owner)
    r))

(defn open-screen!
  "Open the preset editor as a reactive overlay screen."
  ([owner]
   (let [^UiRt r (create-runtime owner)]
     (bridge/open-reactive-screen! r (local "name")
       {:on-close #(do (clear-selector! r)
                       (untrack-active! owner)
                       (logic/close-screen! owner))}))))

(defn on-close!
  [owner]
  (untrack-active! owner)
  (logic/close-screen! owner))
