(ns cn.li.mcmod.gui.metadata.registry
  "GUI metadata registry-focused entrypoint extracted from gui.dsl."
  (:require [cn.li.mcmod.gui.dsl :as gui-dsl]))

(def register-gui! gui-dsl/register-gui!)
(def get-gui gui-dsl/get-gui)
(def list-guis gui-dsl/list-guis)
(def get-gui-by-gui-id gui-dsl/get-gui-by-gui-id)
(def list-gui-ids gui-dsl/list-gui-ids)
(def get-all-gui-ids gui-dsl/get-all-gui-ids)
(def has-gui-id? gui-dsl/has-gui-id?)
(def get-registry-name gui-dsl/get-registry-name)
(def get-screen-factory-fn-kw gui-dsl/get-screen-factory-fn-kw)
(def get-gui-type gui-dsl/get-gui-type)
(def get-slot-layout gui-dsl/get-slot-layout)
(def get-display-name gui-dsl/get-display-name)
(def get-container-fn gui-dsl/get-container-fn)
(def get-screen-fn gui-dsl/get-screen-fn)
(def get-container-predicate gui-dsl/get-container-predicate)
(def get-payload-sync-apply-fn gui-dsl/get-payload-sync-apply-fn)
(def get-slot-range gui-dsl/get-slot-range)
(def get-gui-by-type gui-dsl/get-gui-by-type)
(def get-gui-id-for-type gui-dsl/get-gui-id-for-type)
(def get-config-by-container gui-dsl/get-config-by-container)
