(ns cn.li.mcmod.gui.metadata.registry
  "GUI metadata registry-focused entrypoint extracted from gui DSL internals."
  (:require [cn.li.mcmod.gui.registry :as gui-registry]))

(def register-gui! gui-registry/register-gui!)
(def get-gui gui-registry/get-gui)
(def list-guis gui-registry/list-guis)
(def get-gui-by-gui-id gui-registry/get-gui-by-gui-id)
(def list-gui-ids gui-registry/list-gui-ids)
(def get-all-gui-ids gui-registry/get-all-gui-ids)
(def has-gui-id? gui-registry/has-gui-id?)
(def get-registry-name gui-registry/get-registry-name)
(def get-screen-factory-fn-kw gui-registry/get-screen-factory-fn-kw)
(def get-gui-type gui-registry/get-gui-type)
(def get-slot-layout gui-registry/get-slot-layout)
(def get-display-name gui-registry/get-display-name)
(def get-container-fn gui-registry/get-container-fn)
(def get-screen-fn gui-registry/get-screen-fn)
(def get-container-predicate gui-registry/get-container-predicate)
(def get-payload-sync-apply-fn gui-registry/get-payload-sync-apply-fn)
(def get-slot-range gui-registry/get-slot-range)
(def get-gui-by-type gui-registry/get-gui-by-type)
(def get-gui-id-for-type gui-registry/get-gui-id-for-type)
(def get-config-by-container gui-registry/get-config-by-container)
