(ns cn.li.mc262.gui.reactive.host)
(defn dispose-overlay! [& _] nil)
(defn create-tech-ui-container-screen [& _] nil)
(defn create-tech-ui-screen [& _] nil)
(defn render! [& _] nil)
(defn init! [& _] nil)