(ns cn.li.ac.ability.skill-config.vecmanip
  "Vector Manipulation skill action tunables for player-facing skill config.")

(def skill-tunable-definitions
  [{:skill-id :directed-shock :id :charge.min-ticks :path "charge.min-ticks" :section-suffix "charge" :type :int :min 0 :default 6 :comment "DirectedShock minimum valid charge ticks."}
   {:skill-id :directed-shock :id :charge.max-accepted-ticks :path "charge.max-accepted-ticks" :section-suffix "charge" :type :int :min 1 :default 50 :comment "DirectedShock maximum accepted release charge ticks."}
   {:skill-id :directed-shock :id :charge.max-tolerant-ticks :path "charge.max-tolerant-ticks" :section-suffix "charge" :type :int :min 1 :default 200 :comment "DirectedShock charge ticks before auto-abort."}
   {:skill-id :directed-shock :id :targeting.raycast-distance :path "targeting.raycast-distance" :section-suffix "targeting" :type :double :min 0.0 :default 3.0 :comment "DirectedShock entity raycast distance."}
   {:skill-id :directed-shock :id :movement.hit-impulse :path "movement.hit-impulse" :section-suffix "movement" :type :double :min 0.0 :default 0.24 :comment "DirectedShock forward hit impulse scale."}
   {:skill-id :directed-shock :id :movement.knockback-y-adjust :path "movement.knockback-y-adjust" :section-suffix "movement" :type :double :default 0.6 :comment "DirectedShock vertical adjustment before knockback normalization."}
   {:skill-id :directed-shock :id :movement.knockback-scale :path "movement.knockback-scale" :section-suffix "movement" :type :double :default -0.7 :comment "DirectedShock knockback velocity scale."}
   {:skill-id :directed-shock :id :movement.knockback-exp-threshold :path "movement.knockback-exp-threshold" :section-suffix "movement" :type :double :min 0.0 :max 1.0 :default 0.25 :comment "DirectedShock exp threshold required for reverse knockback."}
   {:skill-id :directed-shock :id :combat.damage :path "combat.damage" :section-suffix "combat" :type :double-list :min 0.0 :list-count 2 :default [7.0 15.0] :comment "DirectedShock hit damage endpoints."}
   {:skill-id :directed-shock :id :cost.up.cp :path "cost.up.cp" :section-suffix "cost.up" :type :double-list :min 0.0 :list-count 2 :default [50.0 100.0] :comment "DirectedShock up-stage CP cost."}
   {:skill-id :directed-shock :id :cost.up.overload :path "cost.up.overload" :section-suffix "cost.up" :type :double-list :min 0.0 :list-count 2 :default [18.0 12.0] :comment "DirectedShock up-stage overload cost."}
   {:skill-id :directed-shock :id :cooldown.ticks :path "cooldown.ticks" :section-suffix "cooldown" :type :double-list :min 0.0 :list-count 2 :default [60.0 20.0] :comment "DirectedShock cooldown ticks."}
   {:skill-id :directed-shock :id :progression.exp-hit :path "progression.exp-hit" :section-suffix "progression" :type :double :min 0.0 :default 0.0035 :comment "DirectedShock exp gained on hit."}
   {:skill-id :directed-shock :id :progression.exp-miss :path "progression.exp-miss" :section-suffix "progression" :type :double :min 0.0 :default 0.001 :comment "DirectedShock exp gained on miss."}

   {:skill-id :vec-accel :id :charge.max-ticks :path "charge.max-ticks" :section-suffix "charge" :type :int :min 1 :default 20 :comment "VecAccel maximum charge ticks."}
   {:skill-id :vec-accel :id :movement.max-velocity :path "movement.max-velocity" :section-suffix "movement" :type :double :min 0.0 :default 2.5 :comment "VecAccel maximum launch velocity."}
   {:skill-id :vec-accel :id :movement.speed-progress :path "movement.speed-progress" :section-suffix "movement" :type :double-list :list-count 2 :default [0.4 1.0] :comment "VecAccel sine-progress endpoints used by charge speed."}
   {:skill-id :vec-accel :id :movement.pitch-offset-radians :path "movement.pitch-offset-radians" :section-suffix "movement" :type :double :default -0.174533 :comment "VecAccel pitch offset in radians."}
   {:skill-id :vec-accel :id :targeting.ground-check-distance :path "targeting.ground-check-distance" :section-suffix "targeting" :type :double :min 0.0 :default 2.0 :comment "VecAccel downward raycast distance for low-exp ground checks."}
   {:skill-id :vec-accel :id :targeting.groundless-exp-threshold :path "targeting.groundless-exp-threshold" :section-suffix "targeting" :type :double :min 0.0 :max 1.0 :default 0.5 :comment "VecAccel exp threshold that allows launches without ground contact."}
   {:skill-id :vec-accel :id :cost.up.cp :path "cost.up.cp" :section-suffix "cost.up" :type :double-list :min 0.0 :list-count 2 :default [120.0 80.0] :comment "VecAccel up-stage CP cost."}
   {:skill-id :vec-accel :id :cost.up.overload :path "cost.up.overload" :section-suffix "cost.up" :type :double-list :min 0.0 :list-count 2 :default [30.0 15.0] :comment "VecAccel up-stage overload cost."}
   {:skill-id :vec-accel :id :cooldown.ticks :path "cooldown.ticks" :section-suffix "cooldown" :type :double-list :min 0.0 :list-count 2 :default [80.0 50.0] :comment "VecAccel manual cooldown ticks."}
   {:skill-id :vec-accel :id :progression.exp-use :path "progression.exp-use" :section-suffix "progression" :type :double :min 0.0 :default 0.002 :comment "VecAccel exp gained on launch."}

   {:skill-id :directed-blastwave :id :charge.min-ticks :path "charge.min-ticks" :section-suffix "charge" :type :int :min 0 :default 6 :comment "DirectedBlastwave minimum valid charge ticks."}
   {:skill-id :directed-blastwave :id :charge.max-accepted-ticks :path "charge.max-accepted-ticks" :section-suffix "charge" :type :int :min 1 :default 50 :comment "DirectedBlastwave maximum accepted release charge ticks."}
   {:skill-id :directed-blastwave :id :charge.max-tolerant-ticks :path "charge.max-tolerant-ticks" :section-suffix "charge" :type :int :min 1 :default 200 :comment "DirectedBlastwave charge ticks before auto-abort."}
   {:skill-id :directed-blastwave :id :targeting.raycast-distance :path "targeting.raycast-distance" :section-suffix "targeting" :type :double :min 0.0 :default 4.0 :comment "DirectedBlastwave raycast distance."}
   {:skill-id :directed-blastwave :id :combat.aoe-radius :path "combat.aoe-radius" :section-suffix "combat" :type :double :min 0.0 :default 3.0 :comment "DirectedBlastwave entity AOE radius."}
   {:skill-id :directed-blastwave :id :combat.damage :path "combat.damage" :section-suffix "combat" :type :double-list :min 0.0 :list-count 2 :default [10.0 25.0] :comment "DirectedBlastwave AOE damage."}
   {:skill-id :directed-blastwave :id :movement.knockback-y-adjust :path "movement.knockback-y-adjust" :section-suffix "movement" :type :double :default 0.4 :comment "DirectedBlastwave vertical adjustment before knockback normalization."}
   {:skill-id :directed-blastwave :id :movement.knockback-scale :path "movement.knockback-scale" :section-suffix "movement" :type :double :default -1.2 :comment "DirectedBlastwave knockback impulse scale."}
   {:skill-id :directed-blastwave :id :breaking.hardness-low-threshold :path "breaking.hardness-low-threshold" :section-suffix "breaking" :type :double :min 0.0 :max 1.0 :default 0.25 :comment "DirectedBlastwave exp threshold for low hardness cap."}
   {:skill-id :directed-blastwave :id :breaking.hardness-mid-threshold :path "breaking.hardness-mid-threshold" :section-suffix "breaking" :type :double :min 0.0 :max 1.0 :default 0.5 :comment "DirectedBlastwave exp threshold for mid hardness cap."}
   {:skill-id :directed-blastwave :id :breaking.hardness-caps :path "breaking.hardness-caps" :section-suffix "breaking" :type :double-list :min 0.0 :list-count 3 :default [2.9 25.0 55.0] :comment "DirectedBlastwave block hardness caps for low, mid, and high exp."}
   {:skill-id :directed-blastwave :id :breaking.break-probability :path "breaking.break-probability" :section-suffix "breaking" :type :double-list :min 0.0 :max 1.0 :list-count 2 :default [0.5 0.8] :comment "DirectedBlastwave random block break probability."}
   {:skill-id :directed-blastwave :id :breaking.drop-probability :path "breaking.drop-probability" :section-suffix "breaking" :type :double-list :min 0.0 :max 1.0 :list-count 2 :default [0.4 0.9] :comment "DirectedBlastwave block drop probability."}
   {:skill-id :directed-blastwave :id :cost.up.cp :path "cost.up.cp" :section-suffix "cost.up" :type :double-list :min 0.0 :list-count 2 :default [160.0 200.0] :comment "DirectedBlastwave up-stage CP cost."}
   {:skill-id :directed-blastwave :id :cost.up.overload :path "cost.up.overload" :section-suffix "cost.up" :type :double-list :min 0.0 :list-count 2 :default [50.0 30.0] :comment "DirectedBlastwave up-stage overload cost."}
   {:skill-id :directed-blastwave :id :cooldown.ticks :path "cooldown.ticks" :section-suffix "cooldown" :type :double-list :min 0.0 :list-count 2 :default [80.0 50.0] :comment "DirectedBlastwave cooldown ticks."}
   {:skill-id :directed-blastwave :id :progression.exp-hit :path "progression.exp-hit" :section-suffix "progression" :type :double :min 0.0 :default 0.0025 :comment "DirectedBlastwave exp gained when entities are hit."}
   {:skill-id :directed-blastwave :id :progression.exp-miss :path "progression.exp-miss" :section-suffix "progression" :type :double :min 0.0 :default 0.0012 :comment "DirectedBlastwave exp gained when no entities are hit."}

   {:skill-id :groundshock :id :charge.min-ticks :path "charge.min-ticks" :section-suffix "charge" :type :int :min 0 :default 5 :comment "Groundshock minimum charge ticks."}
   {:skill-id :groundshock :id :cost.up.cp :path "cost.up.cp" :section-suffix "cost.up" :type :double-list :min 0.0 :list-count 2 :default [80.0 150.0] :comment "Groundshock up-stage CP cost."}
   {:skill-id :groundshock :id :cost.up.overload :path "cost.up.overload" :section-suffix "cost.up" :type :double-list :min 0.0 :list-count 2 :default [15.0 10.0] :comment "Groundshock up-stage overload cost."}
   {:skill-id :groundshock :id :effect.init-energy :path "effect.init-energy" :section-suffix "effect" :type :double-list :min 0.0 :list-count 2 :default [60.0 120.0] :comment "Groundshock initial propagation energy."}
   {:skill-id :groundshock :id :effect.energy-cost.stone :path "effect.energy-cost.stone" :section-suffix "effect.energy-cost" :type :double :min 0.0 :default 0.4 :comment "Groundshock propagation energy consumed when converting stone."}
   {:skill-id :groundshock :id :effect.energy-cost.grass-block :path "effect.energy-cost.grass-block" :section-suffix "effect.energy-cost" :type :double :min 0.0 :default 0.2 :comment "Groundshock propagation energy consumed when converting grass blocks."}
   {:skill-id :groundshock :id :effect.energy-cost.farmland :path "effect.energy-cost.farmland" :section-suffix "effect.energy-cost" :type :double :min 0.0 :default 0.1 :comment "Groundshock propagation energy consumed when crossing farmland."}
   {:skill-id :groundshock :id :effect.energy-cost.default-block :path "effect.energy-cost.default-block" :section-suffix "effect.energy-cost" :type :double :min 0.0 :default 0.5 :comment "Groundshock propagation energy consumed for other affected blocks."}
   {:skill-id :groundshock :id :effect.max-iterations :path "effect.max-iterations" :section-suffix "effect" :type :double-list :min 1.0 :list-count 2 :default [10.0 25.0] :comment "Groundshock maximum propagation iterations."}
   {:skill-id :groundshock :id :combat.damage :path "combat.damage" :section-suffix "combat" :type :double-list :min 0.0 :list-count 2 :default [4.0 6.0] :comment "Groundshock AOE damage."}
   {:skill-id :groundshock :id :combat.entity-search-radius :path "combat.entity-search-radius" :section-suffix "combat" :type :double :min 0.0 :default 2.0 :comment "Groundshock entity search radius per affected block."}
   {:skill-id :groundshock :id :movement.launch-random-base :path "movement.launch-random-base" :section-suffix "movement" :type :double :min 0.0 :default 0.6 :comment "Groundshock launch base Y velocity."}
   {:skill-id :groundshock :id :movement.launch-random-span :path "movement.launch-random-span" :section-suffix "movement" :type :double :min 0.0 :default 0.3 :comment "Groundshock random launch Y span."}
   {:skill-id :groundshock :id :movement.launch-scale :path "movement.launch-scale" :section-suffix "movement" :type :double-list :min 0.0 :list-count 2 :default [0.8 1.3] :comment "Groundshock launch scale endpoints."}
   {:skill-id :groundshock :id :breaking.ground-break-probability :path "breaking.ground-break-probability" :section-suffix "breaking" :type :double :min 0.0 :max 1.0 :default 0.3 :comment "Groundshock chance to break a ground block in the path."}
   {:skill-id :groundshock :id :breaking.drop-rate :path "breaking.drop-rate" :section-suffix "breaking" :type :double-list :min 0.0 :max 1.0 :list-count 2 :default [0.3 1.0] :comment "Groundshock block drop rate endpoints."}
   {:skill-id :groundshock :id :breaking.mastery-exp-threshold :path "breaking.mastery-exp-threshold" :section-suffix "breaking" :type :double :min 0.0 :max 1.0 :default 1.0 :comment "Groundshock exp threshold for the mastery break ring."}
   {:skill-id :groundshock :id :breaking.mastery-radius :path "breaking.mastery-radius" :section-suffix "breaking" :type :int :min 0 :default 5 :comment "Groundshock mastery ring radius in blocks."}
   {:skill-id :groundshock :id :breaking.mastery-hardness-cap :path "breaking.mastery-hardness-cap" :section-suffix "breaking" :type :double :min 0.0 :default 0.6 :comment "Groundshock mastery ring max hardness."}
   {:skill-id :groundshock :id :cooldown.ticks :path "cooldown.ticks" :section-suffix "cooldown" :type :double-list :min 0.0 :list-count 2 :default [80.0 40.0] :comment "Groundshock cooldown ticks."}
   {:skill-id :groundshock :id :progression.exp-entity :path "progression.exp-entity" :section-suffix "progression" :type :double :min 0.0 :default 0.002 :comment "Groundshock exp gained per affected entity."}
   {:skill-id :groundshock :id :progression.exp-use :path "progression.exp-use" :section-suffix "progression" :type :double :min 0.0 :default 0.001 :comment "Groundshock exp gained per successful use."}

   {:skill-id :blood-retrograde :id :charge.max-ticks :path "charge.max-ticks" :section-suffix "charge" :type :int :min 1 :default 30 :comment "BloodRetrograde max charge ticks before auto-release."}
   {:skill-id :blood-retrograde :id :targeting.distance :path "targeting.distance" :section-suffix "targeting" :type :double :min 0.0 :default 2.0 :comment "BloodRetrograde entity raycast distance."}
   {:skill-id :blood-retrograde :id :targeting.entity-search-radius :path "targeting.entity-search-radius" :section-suffix "targeting" :type :double :min 0.0 :default 4.0 :comment "BloodRetrograde target info refresh radius."}
   {:skill-id :blood-retrograde :id :cost.release.cp :path "cost.release.cp" :section-suffix "cost.release" :type :double-list :min 0.0 :list-count 2 :default [280.0 350.0] :comment "BloodRetrograde release CP cost."}
   {:skill-id :blood-retrograde :id :cost.release.overload :path "cost.release.overload" :section-suffix "cost.release" :type :double-list :min 0.0 :list-count 2 :default [55.0 40.0] :comment "BloodRetrograde release overload cost."}
   {:skill-id :blood-retrograde :id :combat.damage :path "combat.damage" :section-suffix "combat" :type :double-list :min 0.0 :list-count 2 :default [30.0 60.0] :comment "BloodRetrograde direct damage."}
   {:skill-id :blood-retrograde :id :cooldown.ticks :path "cooldown.ticks" :section-suffix "cooldown" :type :double-list :min 0.0 :list-count 2 :default [90.0 40.0] :comment "BloodRetrograde cooldown ticks."}
   {:skill-id :blood-retrograde :id :progression.exp-hit :path "progression.exp-hit" :section-suffix "progression" :type :double :min 0.0 :default 0.002 :comment "BloodRetrograde exp gained on hit."}

   {:skill-id :plasma-cannon :id :charge.time :path "charge.time" :section-suffix "charge" :type :double-list :min 1.0 :list-count 2 :default [60.0 30.0] :comment "PlasmaCannon charge time endpoints."}
   {:skill-id :plasma-cannon :id :cost.tick.cp :path "cost.tick.cp" :section-suffix "cost.tick" :type :double-list :min 0.0 :list-count 2 :default [18.0 25.0] :comment "PlasmaCannon charge CP per tick."}
   {:skill-id :plasma-cannon :id :cost.overload-keep :path "cost.overload-keep" :section-suffix "cost" :type :double-list :min 0.0 :list-count 2 :default [500.0 400.0] :comment "PlasmaCannon overload floor/activation cost."}
   {:skill-id :plasma-cannon :id :targeting.raycast-distance :path "targeting.raycast-distance" :section-suffix "targeting" :type :double :min 0.0 :default 100.0 :comment "PlasmaCannon destination raycast distance."}
   {:skill-id :plasma-cannon :id :projectile.block-hit-extra-distance :path "projectile.block-hit-extra-distance" :section-suffix "projectile" :type :double :min 0.0 :default 0.1 :comment "PlasmaCannon extra block raycast distance per step."}
   {:skill-id :plasma-cannon :id :projectile.max-flight-ticks :path "projectile.max-flight-ticks" :section-suffix "projectile" :type :int :min 1 :default 240 :comment "PlasmaCannon max projectile flight ticks."}
   {:skill-id :plasma-cannon :id :combat.damage :path "combat.damage" :section-suffix "combat" :type :double-list :min 0.0 :list-count 2 :default [80.0 150.0] :comment "PlasmaCannon explosion damage."}
   {:skill-id :plasma-cannon :id :combat.damage-radius :path "combat.damage-radius" :section-suffix "combat" :type :double :min 0.0 :default 10.0 :comment "PlasmaCannon entity damage radius."}
   {:skill-id :plasma-cannon :id :combat.explosion-radius :path "combat.explosion-radius" :section-suffix "combat" :type :double-list :min 0.0 :list-count 2 :default [12.0 15.0] :comment "PlasmaCannon terrain explosion radius."}
   {:skill-id :plasma-cannon :id :cooldown.ticks :path "cooldown.ticks" :section-suffix "cooldown" :type :double-list :min 0.0 :list-count 2 :default [1000.0 600.0] :comment "PlasmaCannon cooldown ticks."}
   {:skill-id :plasma-cannon :id :progression.exp-use :path "progression.exp-use" :section-suffix "progression" :type :double :min 0.0 :default 0.008 :comment "PlasmaCannon exp gained on successful explosion."}

   {:skill-id :storm-wing :id :charge.time :path "charge.time" :section-suffix "charge" :type :double-list :min 1.0 :list-count 2 :default [70.0 30.0] :comment "StormWing charge time endpoints."}
   {:skill-id :storm-wing :id :movement.acceleration :path "movement.acceleration" :section-suffix "movement" :type :double :min 0.0 :default 0.16 :comment "StormWing velocity acceleration step."}
   {:skill-id :storm-wing :id :movement.speed-exp-threshold :path "movement.speed-exp-threshold" :section-suffix "movement" :type :double :min 0.0 :max 1.0 :default 0.45 :comment "StormWing exp threshold for high speed multiplier."}
   {:skill-id :storm-wing :id :movement.speed-multipliers :path "movement.speed-multipliers" :section-suffix "movement" :type :double-list :min 0.0 :list-count 2 :default [0.7 1.2] :comment "StormWing low/high speed multipliers."}
   {:skill-id :storm-wing :id :movement.speed-scale :path "movement.speed-scale" :section-suffix "movement" :type :double-list :min 0.0 :list-count 2 :default [2.0 3.0] :comment "StormWing exp-scaled speed factor."}
   {:skill-id :storm-wing :id :movement.hover-near-ground-velocity :path "movement.hover-near-ground-velocity" :section-suffix "movement" :type :double :default 0.1 :comment "StormWing hover Y velocity near ground."}
   {:skill-id :storm-wing :id :movement.hover-air-velocity :path "movement.hover-air-velocity" :section-suffix "movement" :type :double :default 0.078 :comment "StormWing hover Y velocity in air."}
   {:skill-id :storm-wing :id :targeting.near-ground-distance :path "targeting.near-ground-distance" :section-suffix "targeting" :type :double :min 0.0 :default 2.0 :comment "StormWing near-ground raycast distance."}
   {:skill-id :storm-wing :id :breaking.low-exp-threshold :path "breaking.low-exp-threshold" :section-suffix "breaking" :type :double :min 0.0 :max 1.0 :default 0.15 :comment "StormWing exp threshold below which soft blocks are broken."}
   {:skill-id :storm-wing :id :breaking.soft-block-tries :path "breaking.soft-block-tries" :section-suffix "breaking" :type :int :min 0 :default 40 :comment "StormWing random soft-block break attempts per tick."}
   {:skill-id :storm-wing :id :breaking.soft-block-search-radius :path "breaking.soft-block-search-radius" :section-suffix "breaking" :type :int :min 0 :default 10 :comment "StormWing random soft-block search radius."}
   {:skill-id :storm-wing :id :breaking.soft-hardness-max :path "breaking.soft-hardness-max" :section-suffix "breaking" :type :double :min 0.0 :default 0.3 :comment "StormWing max hardness for random soft-block breaking."}
   {:skill-id :storm-wing :id :combat.mastery-knockback-radius :path "combat.mastery-knockback-radius" :section-suffix "combat" :type :double :min 0.0 :default 3.0 :comment "StormWing max-exp initial knockback radius."}
   {:skill-id :storm-wing :id :combat.mastery-knockback-strength :path "combat.mastery-knockback-strength" :section-suffix "combat" :type :double :min 0.0 :default 2.0 :comment "StormWing max-exp initial knockback strength."}
   {:skill-id :storm-wing :id :cost.tick.cp :path "cost.tick.cp" :section-suffix "cost.tick" :type :double-list :min 0.0 :list-count 2 :default [40.0 25.0] :comment "StormWing active tick CP cost."}
   {:skill-id :storm-wing :id :cost.tick.overload :path "cost.tick.overload" :section-suffix "cost.tick" :type :double-list :min 0.0 :list-count 2 :default [10.0 7.0] :comment "StormWing active tick overload cost."}
   {:skill-id :storm-wing :id :cooldown.ticks :path "cooldown.ticks" :section-suffix "cooldown" :type :double-list :min 0.0 :list-count 2 :default [30.0 10.0] :comment "StormWing cooldown ticks on terminate."}
   {:skill-id :storm-wing :id :progression.exp-tick :path "progression.exp-tick" :section-suffix "progression" :type :double :min 0.0 :default 0.00005 :comment "StormWing exp gained per flight tick."}

   {:skill-id :vec-deviation :id :cost.tick.cp :path "cost.tick.cp" :section-suffix "cost.tick" :type :double-list :min 0.0 :list-count 2 :default [13.0 5.0] :comment "VecDeviation active tick CP cost."}
   {:skill-id :vec-deviation :id :targeting.radius :path "targeting.radius" :section-suffix "targeting" :type :double :min 0.0 :default 5.0 :comment "VecDeviation projectile scan radius."}
   {:skill-id :vec-deviation :id :targeting.affected-entity-difficulty :path "targeting.affected-entity-difficulty" :section-suffix "targeting" :type :string-list :default ["minecraft:arrow:1.0" "minecraft:potion:1.4" "minecraft:snowball:0.1"] :comment "VecDeviation projectile difficulty entries as registry-id:difficulty."}
   {:skill-id :vec-deviation :id :targeting.excluded-entity-ids :path "targeting.excluded-entity-ids" :section-suffix "targeting" :type :string-list :default ["minecraft:item" "minecraft:xp_bottle" "minecraft:experience_bottle"] :comment "VecDeviation registry ids excluded from projectile handling."}
   {:skill-id :vec-deviation :id :targeting.large-fireball-ids :path "targeting.large-fireball-ids" :section-suffix "targeting" :type :string-list :default ["minecraft:fireball" "minecraft:large_fireball"] :comment "VecDeviation large fireball ids that create a small explosion when discarded."}
   {:skill-id :vec-deviation :id :targeting.small-fireball-ids :path "targeting.small-fireball-ids" :section-suffix "targeting" :type :string-list :default ["minecraft:small_fireball"] :comment "VecDeviation small fireball ids that are discarded when deflected."}
   {:skill-id :vec-deviation :id :cost.deflect.cp :path "cost.deflect.cp" :section-suffix "cost.deflect" :type :double-list :min 0.0 :list-count 2 :default [15.0 12.0] :comment "VecDeviation CP cost per projectile difficulty."}
   {:skill-id :vec-deviation :id :combat.fireball-explosion-radius :path "combat.fireball-explosion-radius" :section-suffix "combat" :type :double :min 0.0 :default 1.0 :comment "VecDeviation explosion radius for reflected large fireballs."}
   {:skill-id :vec-deviation :id :combat.damage-ignore-threshold :path "combat.damage-ignore-threshold" :section-suffix "combat" :type :double :min 0.0 :default 9999.0 :comment "VecDeviation damage values above this threshold are not reduced."}
   {:skill-id :vec-deviation :id :combat.damage-reduction :path "combat.damage-reduction" :section-suffix "combat" :type :double-list :min 0.0 :max 1.0 :list-count 2 :default [0.4 0.9] :comment "VecDeviation incoming damage reduction rate."}
   {:skill-id :vec-deviation :id :cost.damage.cp :path "cost.damage.cp" :section-suffix "cost.damage" :type :double-list :min 0.0 :list-count 2 :default [15.0 12.0] :comment "VecDeviation max CP consumed per incoming damage event."}
   {:skill-id :vec-deviation :id :progression.exp-deflect-scale :path "progression.exp-deflect-scale" :section-suffix "progression" :type :double :min 0.0 :default 0.001 :comment "VecDeviation exp gained per projectile difficulty."}
   {:skill-id :vec-deviation :id :progression.exp-damage-scale :path "progression.exp-damage-scale" :section-suffix "progression" :type :double :min 0.0 :default 0.0006 :comment "VecDeviation exp gained per reduced damage."}

   {:skill-id :vec-reflection :id :cost.tick.cp :path "cost.tick.cp" :section-suffix "cost.tick" :type :double-list :min 0.0 :list-count 2 :default [15.0 11.0] :comment "VecReflection active tick CP cost."}
   {:skill-id :vec-reflection :id :cost.overload-keep :path "cost.overload-keep" :section-suffix "cost" :type :double-list :min 0.0 :list-count 2 :default [350.0 250.0] :comment "VecReflection overload floor while active."}
   {:skill-id :vec-reflection :id :targeting.radius :path "targeting.radius" :section-suffix "targeting" :type :double :min 0.0 :default 4.0 :comment "VecReflection projectile scan radius."}
   {:skill-id :vec-reflection :id :targeting.affected-entity-difficulty :path "targeting.affected-entity-difficulty" :section-suffix "targeting" :type :string-list :default ["minecraft:arrow:1.0" "minecraft:potion:1.4" "minecraft:snowball:0.1"] :comment "VecReflection projectile difficulty entries as registry-id:difficulty."}
   {:skill-id :vec-reflection :id :targeting.excluded-entity-ids :path "targeting.excluded-entity-ids" :section-suffix "targeting" :type :string-list :default ["minecraft:item" "minecraft:xp_bottle" "minecraft:experience_bottle"] :comment "VecReflection registry ids excluded from projectile handling."}
  {:skill-id :vec-reflection :id :targeting.large-fireball-ids :path "targeting.large-fireball-ids" :section-suffix "targeting" :type :string-list :default ["minecraft:fireball" "minecraft:large_fireball"] :comment "VecReflection large fireball ids that should be replaced by spawned projectiles."}
  {:skill-id :vec-reflection :id :targeting.small-fireball-ids :path "targeting.small-fireball-ids" :section-suffix "targeting" :type :string-list :default ["minecraft:small_fireball"] :comment "VecReflection small fireball ids that should be replaced by spawned projectiles."}
   {:skill-id :vec-reflection :id :cost.reflect-entity.cp :path "cost.reflect-entity.cp" :section-suffix "cost.reflect-entity" :type :double-list :min 0.0 :list-count 2 :default [300.0 160.0] :comment "VecReflection CP cost per reflected projectile difficulty."}
   {:skill-id :vec-reflection :id :combat.damage-multiplier :path "combat.damage-multiplier" :section-suffix "combat" :type :double-list :min 0.0 :list-count 2 :default [0.6 1.2] :comment "VecReflection incoming damage reflection multiplier."}
   {:skill-id :vec-reflection :id :combat.min-reflected-damage :path "combat.min-reflected-damage" :section-suffix "combat" :type :double :min 0.0 :default 1.0 :comment "VecReflection minimum reflected damage required to perform."}
   {:skill-id :vec-reflection :id :cost.damage.cp :path "cost.damage.cp" :section-suffix "cost.damage" :type :double-list :min 0.0 :list-count 2 :default [20.0 15.0] :comment "VecReflection CP consumed per incoming damage point."}
   {:skill-id :vec-reflection :id :progression.exp-reflect-entity-scale :path "progression.exp-reflect-entity-scale" :section-suffix "progression" :type :double :min 0.0 :default 0.0008 :comment "VecReflection exp gained per reflected projectile difficulty."}
   {:skill-id :vec-reflection :id :progression.exp-damage-scale :path "progression.exp-damage-scale" :section-suffix "progression" :type :double :min 0.0 :default 0.0004 :comment "VecReflection exp gained per reflected damage."}])

(def internal-tunable-definitions
  [{:skill-id :directed-shock :id :targeting.eye-height :path "targeting.eye-height" :section-suffix "targeting" :type :double :min 0.0 :default 1.62 :comment "Internal target eye height fallback."}
   {:skill-id :directed-blastwave :id :charge.punch-anim-ticks :path "charge.punch-anim-ticks" :section-suffix "charge" :type :int :min 0 :default 6 :comment "Internal punch animation ticks before termination."}
   {:skill-id :directed-blastwave :id :targeting.eye-height :path "targeting.eye-height" :section-suffix "targeting" :type :double :min 0.0 :default 1.62 :comment "Internal target eye height fallback."}
   {:skill-id :blood-retrograde :id :charge.fx-ratio-ticks :path "charge.fx-ratio-ticks" :section-suffix "charge" :type :double :min 0.001 :default 20.0 :comment "Internal charge ticks mapped to full FX ratio."}
   {:skill-id :blood-retrograde :id :targeting.fallback-width :path "targeting.fallback-width" :section-suffix "targeting" :type :double :min 0.0 :default 0.6 :comment "Internal fallback entity width."}
   {:skill-id :blood-retrograde :id :targeting.fallback-height :path "targeting.fallback-height" :section-suffix "targeting" :type :double :min 0.0 :default 1.8 :comment "Internal fallback entity height."}
   {:skill-id :blood-retrograde :id :targeting.fallback-eye-height :path "targeting.fallback-eye-height" :section-suffix "targeting" :type :double :min 0.0 :default 1.62 :comment "Internal fallback entity eye height."}
   {:skill-id :blood-retrograde :id :effect.spray-angles :path "effect.spray-angles" :section-suffix "effect" :type :double-list :list-count 9 :default [0.0 30.0 45.0 60.0 80.0 -30.0 -45.0 -60.0 -80.0] :comment "Internal spray pitch angles."}
   {:skill-id :plasma-cannon :id :targeting.eye-height :path "targeting.eye-height" :section-suffix "targeting" :type :double :min 0.0 :default 1.62 :comment "Internal raycast eye height."}
   {:skill-id :plasma-cannon :id :projectile.spawn-y-offset :path "projectile.spawn-y-offset" :section-suffix "projectile" :type :double :default 15.0 :comment "Internal projectile spawn Y offset."}
   {:skill-id :plasma-cannon :id :projectile.destination-epsilon :path "projectile.destination-epsilon" :section-suffix "projectile" :type :double :min 0.0 :default 1.5 :comment "Internal destination epsilon."}
   {:skill-id :plasma-cannon :id :projectile.sync-interval-ticks :path "projectile.sync-interval-ticks" :section-suffix "projectile" :type :int :min 1 :default 5 :comment "Internal projectile FX sync interval."}
   {:skill-id :storm-wing :id :targeting.near-ground-eye-height :path "targeting.near-ground-eye-height" :section-suffix "targeting" :type :double :min 0.0 :default 1.62 :comment "Internal near-ground raycast eye height."}
  {:skill-id :vec-reflection :id :targeting.attacker-search-radius :path "targeting.attacker-search-radius" :section-suffix "targeting" :type :double :min 0.0 :default 20.0 :comment "Internal attacker lookup radius for FX."}
  {:skill-id :vec-reflection :id :interaction.projectile-arbitration-priority :path "interaction.projectile-arbitration-priority" :section-suffix "interaction" :type :string-list :default ["reflection-first"] :comment "Internal dual-active arbitration priority (reflection-first or deviation-first)."}
  {:skill-id :vec-reflection :id :combat.max-reflections :path "combat.max-reflections" :section-suffix "combat" :type :int :min 1 :default 6 :comment "Internal maximum nested reflection depth before stopping recursion."}
  {:skill-id :vec-reflection :id :tracking.visited-ttl-ticks :path "tracking.visited-ttl-ticks" :section-suffix "tracking" :type :int :min 1 :default 40 :comment "Internal visited-entity TTL (ticks) before cleanup."}
  {:skill-id :vec-reflection :id :tracking.visited-max-size :path "tracking.visited-max-size" :section-suffix "tracking" :type :int :min 16 :default 256 :comment "Internal max size for visited-entity tracking map."}])
