(ns cn.li.ac.gui.platform-adapter.registry-api
  "Registry and container-tracking API exported to platform integration."
  (:require [cn.li.ac.wireless.gui.registry :as registry]))

(def get-gui-handler registry/get-gui-handler)
(def register-gui-handler registry/register-gui-handler)
(def init-gui-handler! registry/init!)
(def register-active-container! registry/register-active-container!)
(def unregister-active-container! registry/unregister-active-container!)
(def register-player-container! registry/register-player-container!)
(def unregister-player-container! registry/unregister-player-container!)
(def get-active-container (fn [_player] nil))
(def list-active-containers (fn [] #{}))
(def get-player-container registry/get-player-container)
(def get-player-container-from-active registry/get-player-container-from-active)
(def get-container-for-menu registry/get-container-for-menu)
(def register-menu-container! registry/register-menu-container!)
(def unregister-menu-container! registry/unregister-menu-container!)
(def register-container-by-id! registry/register-container-by-id!)
(def unregister-container-by-id! registry/unregister-container-by-id!)
(def get-container-by-id registry/get-container-by-id)
(def get-menu-container-id registry/get-menu-container-id)
(def get-client-container registry/get-client-container)
(def set-client-container! registry/set-client-container!)
(def clear-client-container! registry/clear-client-container!)
(def apply-container-sync-packet registry/apply-container-sync-packet)
(def client-container registry/get-client-container)
