(ns cn.li.mcmod.runtime.hooks.client-ui
  "Client UI/runtime interaction hook surface (delegates to hooks-core during migration)."
  (:require [cn.li.mcmod.runtime.hooks-core :as hooks-core]))

(def client-build-overlay-plan hooks-core/client-build-overlay-plan)
(def client-build-hud-render-data hooks-core/client-build-hud-render-data)
(def client-open-skill-tree-screen! hooks-core/client-open-skill-tree-screen!)
(def client-build-skill-tree-draw-ops hooks-core/client-build-skill-tree-draw-ops)
(def client-handle-skill-tree-hover! hooks-core/client-handle-skill-tree-hover!)
(def client-handle-skill-tree-click! hooks-core/client-handle-skill-tree-click!)
(def client-close-skill-tree-screen! hooks-core/client-close-skill-tree-screen!)
(def client-open-preset-editor-screen! hooks-core/client-open-preset-editor-screen!)
(def client-build-preset-editor-draw-ops hooks-core/client-build-preset-editor-draw-ops)
(def client-handle-preset-editor-click! hooks-core/client-handle-preset-editor-click!)
(def client-close-preset-editor-screen! hooks-core/client-close-preset-editor-screen!)
(def client-open-location-teleport-screen! hooks-core/client-open-location-teleport-screen!)
(def client-build-location-teleport-draw-ops hooks-core/client-build-location-teleport-draw-ops)
(def client-handle-location-teleport-click! hooks-core/client-handle-location-teleport-click!)
(def client-close-location-teleport-screen! hooks-core/client-close-location-teleport-screen!)
(def client-trigger-mode-switch! hooks-core/client-trigger-mode-switch!)
(def client-trigger-preset-switch! hooks-core/client-trigger-preset-switch!)
